# Generated by Django 2.1.5 on 2019-01-13 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('dhara', models.CharField(default='', max_length=100)),
                ('crime_no', models.CharField(default='', max_length=50)),
                ('date_of_dakhila', models.DateField(blank=True, null=True)),
                ('by', models.CharField(default='', max_length=100)),
                ('banam', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_description', models.CharField(default='', max_length=500)),
                ('rack_no', models.CharField(default='', max_length=50)),
                ('shelf_no', models.CharField(default='', max_length=50)),
                ('box_no', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vivechak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter 10 digits number only.', regex='^(\\d{10})$')])),
                ('adharcard', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter 12 digits number only.', regex='^(\\d{12})$')])),
                ('pancard', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Length should be 10.', regex='^(.{10})$')])),
            ],
        ),
    ]
