# Generated by Django 2.1.5 on 2019-01-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_report_vivechak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date_of_dakhila',
            new_name='date_Of_Dakhila',
        ),
    ]
