# Generated by Django 2.1.5 on 2019-01-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190113_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date_Of_Dakhila',
            new_name='date_of_dakhila',
        ),
    ]
