# Generated by Django 2.1.5 on 2019-01-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190113_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vivechak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Vivechak'),
        ),
    ]
