# Generated by Django 2.1.5 on 2019-01-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190113_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vivechak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Vivechak'),
        ),
    ]
