# Generated by Django 2.1.5 on 2019-01-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190113_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vivechak',
            field=models.CharField(default='', max_length=100),
        ),
    ]
