# Generated by Django 2.1.5 on 2019-01-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190113_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('entry_date_and_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='vivechak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Vivechak'),
        ),
    ]
