# Generated by Django 2.1.5 on 2019-01-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190114_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_dakhila',
            field=models.DateField(null=True),
        ),
    ]
