# Generated by Django 2.1.5 on 2019-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190114_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('exit_date_and_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='StockIn',
        ),
    ]
