# Generated by Django 2.1.5 on 2019-01-14 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190114_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='entry_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 17, 47, 7, 85998)),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='exit_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 17, 47, 7, 85998)),
        ),
    ]
