# Generated by Django 2.1.5 on 2019-01-14 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190114_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='entry_date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='exit_date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
