# Generated by Django 2.1.5 on 2019-01-21 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir', models.CharField(max_length=100)),
                ('thana', models.CharField(max_length=50)),
                ('maal_type', models.CharField(choices=[('वस्तू', 'वस्तू'), ('शराब', 'शराब'), ('नशीला पदार्थ', 'नशीला पदार्थ'), ('अन्य', 'अन्य')], max_length=50)),
                ('if_other', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to='maal_images')),
                ('seizure_date', models.DateField(null=True)),
                ('under_section', models.CharField(max_length=100)),
                ('act', models.CharField(choices=[('IPC', 'ipc'), ('option2', 'option2'), ('option3', 'option3')], max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in trial', 'in trial'), ('completed', 'completed'), ('option3', 'option3')], max_length=50)),
                ('court', models.CharField(max_length=100)),
                ('date_of_disposal', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vivechak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pradesh', models.CharField(max_length=100)),
                ('jila', models.CharField(max_length=100)),
                ('vibhag', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('subunit', models.CharField(max_length=100)),
                ('pno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('adharcard', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter 12 digits number only.', regex='^(\\d{12})$')])),
                ('pancard', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Length should be 10.', regex='^(.{10})$')])),
            ],
        ),
        migrations.AddField(
            model_name='maalmodel',
            name='vivechak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Vivechak'),
        ),
    ]
