# Generated by Django 2.1.5 on 2019-01-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maalmodel',
            name='act',
            field=models.CharField(choices=[('IPC', 'ipc'), ('option2', 'option2'), ('option3', 'option3')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maalmodel',
            name='status',
            field=models.CharField(choices=[('in trial', 'in trial'), ('completed', 'completed'), ('option3', 'option3')], max_length=50),
        ),
    ]
